;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-kill-sentence
        forward-sexp
        magit-status
        mark-whole-buffer
        mc/mark-all-in-region-regexp
        rekenerd-move-beginning-of-line
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        ido-switch-buffer
        indent-for-tab-command
        previous-buffer
        rk/move-beginning-of-line
        ))
