(source gnu)
(source melpa)

(depends-on "cask")
(depends-on "company")
(depends-on "exec-path-from-shell")
(depends-on "grizzl")
(depends-on "guru-mode")
(depends-on "magit")
(depends-on "pallet")
(depends-on "projectile")
(depends-on "smex")
(depends-on "zenburn-theme")
